name: standardjs_test

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run StandardJS with threshold (no file, no env)
        run: |
          npm run -s standard -- --reporter=standard-json 2>/dev/null || true | node -e "
          const fs = require('fs');

          const txt = (() => { try { return fs.readFileSync(0, 'utf8'); } catch { return ''; } })().trim() || '[]';
          let data; try { data = JSON.parse(txt); } catch { data = []; }

          let errors = 0, warnings = 0;
          for (const file of data) {
            for (const m of (file.messages || [])) {
              if (m.severity === 2) errors++;
              else if (m.severity === 1) warnings++;
            }
          }

          console.log('StandardJS errors:', errors);
          console.log('StandardJS warnings:', warnings);

          const LIMIT = 1000;
          if (errors > LIMIT) {
            console.error(\`Too many errors: \${errors} > \${LIMIT}\`);
            process.exit(1);
          } else {
            console.log(\`Within threshold: \${errors} ≤ \${LIMIT}\`);
          }"