name: standardjs_test

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run StandardJS with threshold
        run: |
          npm run standard -- --reporter=standard-json > standard-report.json || true

          # Parse JSON and enforce ≤1000 error threshold
          node -e "
          const fs = require('fs');
          const path = 'standard-report.json';
          const data = fs.existsSync(path) ? JSON.parse(fs.readFileSync(path, 'utf8')) : [];
          let errors = 0;
          for (const file of data) {
            if (!file || !file.messages) continue;
            for (const m of file.messages) {
              if (m && m.severity === 2) errors++;
            }
          }
          console.log('StandardJS errors:', errors);
          const LIMIT = 1000;
          if (errors > LIMIT) {
            console.error(\`Too many errors: \${errors} > \${LIMIT}\`);
            process.exit(1);
          } else {
            console.log(\`Within threshold: \${errors} ≤ \${LIMIT}\`);
          }"